#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Regenerate the third-party licence texts in docs/licenses/:
#   rust-dependencies.txt   crates linked into msl-guest (cargo-about; guest/about.toml)
#   swift-dependencies.txt  SwiftPM packages msl/msld are built from (Package.resolved)
# Run after changing guest/Cargo.lock or Package.resolved, and commit the result.
# Needs: cargo install --locked --features cli cargo-about
set -eu
ROOT=$(cd "$(dirname "$0")/.." && pwd)
export PATH=/opt/homebrew/opt/rustup/bin:$HOME/.cargo/bin:$PATH
OUT=$ROOT/docs/licenses

(cd "$ROOT/guest" && cargo about generate --workspace about.hbs -o "$OUT/rust-dependencies.txt")

cd "$ROOT"
swift package resolve >/dev/null
{
  echo "Third-party Swift packages in msl and msld (generated by scripts/gen-licenses.sh; do not edit)"
  echo "==============================================================================================="
  swift package show-dependencies --format json 2>/dev/null | python3 -c '
import json, sys
seen = {}
def walk(n):
    for d in n.get("dependencies", []):
        seen[d["identity"]] = (d["url"], d["version"], d["path"])
        walk(d)
walk(json.load(sys.stdin))
for ident in sorted(seen):
    url, ver, path = seen[ident]
    print("\t".join([ident, url, ver, path]))' |
  while IFS="$(printf '\t')" read -r ident url ver path; do
    for f in "$path"/LICENSE* "$path"/LICENCE* "$path"/COPYING* "$path"/NOTICE*; do
      [ -f "$f" ] || continue
      printf '\n-------------------------------------------------------------------------------\n'
      printf '%s %s (%s): %s\n' "$ident" "$ver" "$url" "$(basename "$f")"
      printf -- '-------------------------------------------------------------------------------\n\n'
      cat "$f"
    done
  done
} > "$OUT/swift-dependencies.txt"
echo "wrote $OUT/rust-dependencies.txt and $OUT/swift-dependencies.txt"
