# Homebrew formula (generated by scripts/package.sh; publish it in a tap).
class Msl < Formula
  desc "macOS Subsystem for Linux: the wsl.exe command line on Virtualization.framework"
  homepage "https://github.com/OWNER/msl"
  url "file:///Users/akshay/Projects/msl/dist/msl-0.1.0-macos-arm64.tar.gz"
  sha256 "317288fbe923b7fced76512a08e749d3c0fbbd233829e2de487b6db81fcb8c3b"
  version "0.1.0"

  depends_on arch: :arm64
  depends_on macos: :tahoe # macOS 26+

  def install
    prefix.install "bin", "libexec", "share"
  end

  test do
    assert_match "Usage: msl", shell_output("#{bin}/msl --help")
  end
end
